version: "2"
services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: opencoverage
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_DB: opencoverage

  api:
    build:
      context: .
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      PUBLIC_URL: https://open-coverage.org
      DSN: postgresql://opencoverage:secret@postgres:5432/opencoverage?sslmode=disable
      SCM: github
      GITHUB_APP_PEM_FILE: /app/cov.pem
      GITHUB_APP_ID: "96444"
      GITHUB_DEFAULT_INSTALLATION_ID: "14109303"
      ROOT_PATH: /api
      CORS: '["http://localhost:8080"]'
    volumes:
      - ${PWD}/cov.pem:/app/cov.pem
    depends_on:
      - postgres
    links:
      - postgres

  frontend:
    build:
      context: app
      # dockerfile: app/Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    depends_on:
      - api
    links:
      - api

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 8080:80
      - 443:443
    expose:
      - 8080
      - 443
    depends_on:
      - api
      - frontend
    links:
      - api
      - frontend
